Repository intuit/Tank, pull requests merged in 2025-01, with the labels that each got.

#351 CVE-2024-38827
  proxy-parent/owasp-proxy/pom.xml
  proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/http/dao/JdbcMessageDAO.java
  proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/util/BouncyCastleCertificateUtils.java
Labels: enhancement

#362 Remove Response Body Regex Check
  agent/apiharness/src/main/java/com/intuit/tank/runner/method/RequestRunner.java
Labels: enhancement

#363 Update doPUT to add boundary to multi-part + add doPatch
  agent/agent_common/src/main/java/com/intuit/tank/http/BaseRequest.java
  agent/agent_common/src/main/java/com/intuit/tank/http/TankHttpClient.java
  agent/agent_common/src/test/java/com/intuit/tank/http/MockTankHttpClient.java
  agent/apiharness/src/main/java/com/intuit/tank/runner/method/RequestRunner.java
  agent/apiharness/src/test/java/com/intuit/tank/runner/TestHttpClient.java
  agent/http_client_3/src/main/java/com/intuit/tank/httpclient3/TankHttpClient3.java
  agent/http_client_4/src/main/java/com/intuit/tank/httpclient4/TankHttpClient4.java
  agent/http_client_jdk/src/main/java/com/intuit/tank/httpclientjdk/TankHttpClientJDK.java
Labels: enhancement

#364 pom updates
  data_model/pom.xml
  pom.xml
  web/web_support/pom.xml
Labels: enhancement

#365 Reduce calls to `UUID.randomUUID`
  agent/apiharness/src/main/java/com/intuit/tank/harness/logging/LogEvent.java
  agent/apiharness/src/main/java/com/intuit/tank/runner/TestPlanRunner.java
  agent/apiharness/src/test/java/com/intuit/tank/harness/logging/LogEventTest.java
Labels: enhancement

#366 Use native Servlet 3.0 File Uploader
  agent/agent_common/pom.xml
  agent/agent_common/src/main/java/com/intuit/tank/http/TankHttpUtil.java
  pom.xml
  web/web_ui/pom.xml
  web/web_ui/src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#352 Capture and Log Proxy Response Time in Agent Debugger
  agent/agent_common/src/main/java/com/intuit/tank/http/BaseResponse.java
  agent/agent_common/src/test/java/com/intuit/tank/http/BaseResponseTest.java
  agent/http_client_3/src/main/java/com/intuit/tank/httpclient3/TankHttpClient3.java
  agent/http_client_4/src/main/java/com/intuit/tank/httpclient4/TankHttpClient4.java
  agent/http_client_jdk/src/main/java/com/intuit/tank/httpclientjdk/TankHttpClientJDK.java
  tools/agent_debugger/src/main/java/com/intuit/tank/tools/debugger/ActionProducer.java
  tools/agent_debugger/src/main/java/com/intuit/tank/tools/debugger/AgentDebuggerFrame.java
Labels: enhancement

#367 Fix AgentDebugger Typo
  tools/agent_debugger/src/main/java/com/intuit/tank/tools/debugger/ActionProducer.java
Labels: bug

#368 Updating lucene version
  pom.xml
Labels: bug

#369 Restore commons.fileupload
  agent/agent_common/pom.xml
  agent/agent_common/src/main/java/com/intuit/tank/http/TankHttpUtil.java
  api/src/main/java/com/intuit/tank/storage/S3FileStorage.java
  pom.xml
  rest-mvc/impl/pom.xml
  rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/util/ScriptServiceUtil.java
  script_processor/src/main/java/com/intuit/tank/script/util/ScriptServiceUtil.java
  web/web_support/pom.xml
Labels: bug

#370 h2 2.0 migration
  data_access/src/test/resources/META-INF/persistence.xml
  pom.xml
  web/web_support/src/test/resources/META-INF/persistence.xml
Labels: enhancement, dependencies
